### ISSUE TITLE
Release 2.0.2 Redirect is not working

### ISSUE THREAD

**Issue by jega-ms** [Milad-Akarie/auto_route_library#506] opened 2021-05-01 03:55 UTC
After upgrading to 2.0.2 version. Page redirect is not working.  the below router code is not redirecting to login page and sub router is always loading dashboard route.  

Could you please fix it. 

Example Repo : https://github.com/jega-ms/flutter_web_examples

```dart 
   
@MaterialAutoRouter(
  replaceInRouteName: 'Page,Route',
  routes: <AutoRoute>[
    AutoRoute(page: Landing, initial: true ),
    RedirectRoute(path: '', redirectTo: '/login'),
    AutoRoute(page: LoginPage, path: '/login'),
    AutoRoute(page: RegistrationPage, path: '/register'),
    AutoRoute(
        name: "MyAccountRouter",
        path: "/acc",
        page: MyAccountPage,
        guards: [
          AuthGuard
        ],
        children: [
          AutoRoute(path: 'dashboard', page: DashboardPage, initial: true),
          AutoRoute(path: 'settings', page: SettingsScreen),
          RedirectRoute(path: '', redirectTo: 'dashboard'),
          AutoRoute(path: '*', page: PageNotFound),
        ])
  ],
)
class $AppRouter {}

```

**Comment by theweiweiway** [comment] 2021-05-06 01:18
This is fixed in 2.1.0 - please check and close if working as intended

**Closed** 2022-06-07 08:22 UTC
Labels: no-issue-activity
