### ISSUE TITLE
When using setPathUrlStrategy() refreshing web page or navigating by path from browser pages not loading 

### ISSUE THREAD

**Issue by vipafattal** [Milad-Akarie/auto_route_library#1358] opened 2023-02-16 17:13 UTC

**Comment by shemhazai** [comment] 2023-02-24 12:44
Duplicate of https://github.com/Milad-Akarie/auto_route_library/issues/1361.

--
This issue is resolved in flutter 3.7.4, please have a look at the release notes:

https://github.com/flutter/flutter/wiki/Hotfixes-to-the-Stable-Channel#374-feb-21-2023

**Closed** 2023-05-04 08:21 UTC
Labels: no-issue-activity
