### ISSUE TITLE
Issue "Error: Required named parameter 'type' must be provided." when deploying Flutter in Netlify

### ISSUE THREAD

**Issue by RizaldiWiratama** [Milad-Akarie/auto_route_library#659] opened 2021-08-20 02:37 UTC
Hey @Milad-Akarie, this is a great package for managing route 

Previously I managed to deploying flutter on netlify until yesterday it failed with error message:

> "Error: Required named parameter 'type' must be provided. 
>   ?.routerReportsNewRouteInformation( "

this is deploy log on netlify
![image](https://user-images.githubusercontent.com/23089248/130169276-97931929-d179-45ca-b959-57aab31ef6a8.png)

Strange this error is not appear when i run flutter in my devices / local browser

this is my dependencies for auto route package

```
dependencies:
   auto_route: ^2.3.0
   ...

dependency_overrides:
  meta: ^1.7.0

dev_dependencies:
   auto_route_generator: ^2.3.0
   build_runner: ^2.0.5
   ...
```

and this is my AppRouter.dart
```
@MaterialAutoRouter(
  replaceInRouteName: 'Page,Route',
  routes: <AutoRoute>[


    ///After modify/add new route, run "flutter packages pub run build_runner watch" in terminal to generate new route
    ///or Run "flutter packages pub run build_runner watch --delete-conflicting-outputs" when conflicting output detected

    ///Login
    AutoRoute(page: LoginPage, path: "/login"),

    ///MainNavigationPage
    AutoRoute(page: MainNavigationPage, guards: [AuthGuard], path: "/",
        children: [
          ///Dashboard
          AutoRoute(page: DashboardPage, path: "dashboard", initial: true),

          ///ITSP
          AutoRoute(page: ItspCompanyPage, path: "itsp"),
          AutoRoute(page: ItspRkuPage, path: "itsp/:companyName/rku/"),
          AutoRoute(page: ItspRktPage, path: "itsp/:companyName/rku/:rkuYear/rkt/"),
          AutoRoute(page: ItspRktDetailPage, path: "itsp/:companyName/rku/:rkuYear/rkt/:rktYear/"),
          AutoRoute(page: ItspTallyAddPage, path: "itsp/:companyName/rku/:rkuYear/rkt/:rktYear/add"),
          AutoRoute(page: ItspTallyUpdatePage, path: "itsp/:companyName/rku/:rkuYear/rkt/:rktYear/update/:tallyId"),

          ///Logging
          AutoRoute(page: LoggingOverviewPage, path: "logging"),
          AutoRoute(page: LoggingListPage, path: "logging/list"),
          AutoRoute(page: LoggingAddPAge, path: "logging/list/add"),
          AutoRoute(page: LoggingOverviewDetailPage, path: "logging/:companyId"),

          ///Template Form & List
          AutoRoute(page: FormPage, path: "form"),
          AutoRoute(page: ListPage, path: "list"),

          ///Redirect to Initial Route (Dashboard) if route name is not detected
          RedirectRoute(path: '*', redirectTo: '')
        ]
    ),
  ],
)
class $AppRouter {}
```

is this error related with auto route package? do you have any suggestion about this error? thanks @Milad-Akarie

**Comment by RizaldiWiratama** [comment] 2021-08-20 04:58
After many attempts, I found the problem, the error appears when Netlify update the flutter

my assumption that the latest update of flutter (or a new branch) that got pulled has a conflict with package autoroute 

so the workaround is deleting "git pull" (so Netlify not updating flutter) in Netlify build command and redeploy site.

Build Command (Failed) : 
`if cd flutter; then git pull && cd ..; else git clone https://github.com/flutter/flutter.git; fi && flutter/bin/flutter config --enable-web && flutter/bin/flutter build web --release`

Build Command (Success) :
`if cd flutter; then cd ..; else git clone https://github.com/flutter/flutter.git; fi && flutter/bin/flutter config --enable-web && flutter/bin/flutter build web --release`

**Comment by LefebvreIlyas** [comment] 2021-08-20 09:55
Hello @RizaldiWiratama,

This is caused by flutter/flutter/pull/88122.

**Comment by RizaldiWiratama** [comment] 2021-08-20 22:54
thanks @LefebvreIlyas for the info, so a new update of Widget "Router" Flutter makes package autoroute fails to compile? 

is any workaround for package autoroute for that case ? @Milad-Akarie

**Comment by LefebvreIlyas** [comment] 2021-08-22 10:26
You're welcome @RizaldiWiratama.

The break comes more precisely from the `RouteInformationProvider` class. The package code must be adapted to be compatible.

At the moment, this change is only effective on master if I'm not mistaken, so a solution would be to switch to the beta or dev branch, or even stable, if you don't use anything new that is not yet available there (`flutter channel [branch_name]`).

**Comment by guyluz11** [comment] 2021-09-09 12:42
I got the [same error](https://forum.snapcraft.io/t/snapcraft-with-plugin-flutter-suddenly-crashing/26100/2) while using Snapcraft to package my flutter app.
Changing to the stable worked for me.

Thanks

**Comment by Ruzo** [comment] 2021-09-16 15:04
> You're welcome @RizaldiWiratama.
> 
> The break comes more precisely from the `RouteInformationProvider` class. The package code must be adapted to be compatible.
> 
> At the moment, this change is only effective on master if I'm not mistaken, so a solution would be to switch to the beta or dev branch, or even stable, if you don't use anything new that is not yet available there (`flutter channel [branch_name]`).

Beta does not work either. Only stable does.

**Comment by Hacker437** [comment] 2021-11-28 13:44
> You can use this fork for now https://github.com/biklas7/auto_route_library/tree/chore/update-flutter-beta it's been working for me with the latest flutter beta version.

@biklas7 How to use this folk in pubspec 
`Error on line 19, column 11: Invalid description in the "auto_route_generator" pubspec on the "auto_route" dependency: "../auto_route" is a relative path, but this isn't a local pubspec.
   ╷
19 │     path: ../auto_route
   │           ^^^^^^^^^^^^^
   ╵
pub get failed (65;    ╵)
exit code 65`

I get the following error

**Comment by biklas7** [comment] 2021-11-28 13:51
@Hacker437 I use it like this:

```
dependencies:
  auto_route: ^3.1.3

dependency_overrides:
  auto_route:
    git:
      url: git@github.com:biklas7/auto_route_library.git
      ref: chore/update-flutter-beta
      path: auto_route

dev_dependencies:
  auto_route_generator: ^3.1.0
```

**Comment by Hacker437** [comment] 2021-11-28 14:51
> @Hacker437 I use it like this:
> 
> ```
> dependencies:
>   auto_route: ^3.1.3
> 
> dependency_overrides:
>   auto_route:
>     git:
>       url: git@github.com:biklas7/auto_route_library.git
>       ref: chore/update-flutter-beta
>       path: auto_route
> 
> dev_dependencies:
>   auto_route_generator: ^3.1.0
> ```

Thank you

**Comment by szymonmazanik** [comment] 2021-12-09 10:35
so, now it's also broken on stable channel

**Comment by giiyms** [comment] 2021-12-09 11:32
> @Hacker437 I use it like this:
> 
> ```
> dependencies:
>   auto_route: ^3.1.3
> 
> dependency_overrides:
>   auto_route:
>     git:
>       url: git@github.com:biklas7/auto_route_library.git
>       ref: chore/update-flutter-beta
>       path: auto_route
> 
> dev_dependencies:
>   auto_route_generator: ^3.1.0
> ```

Interesting doesn't work for me. 

```
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.
```

Any ideas how to fix that?

**Comment by biklas7** [comment] 2021-12-09 11:39
> Interesting doesn't work for me.
> 
> ```
> git@github.com: Permission denied (publickey).
> fatal: Could not read from remote repository.
> ```
> 
> Any ideas how to fix that?

The repo is public so it should work. Do you have git set up on your terminal? Maybe check [this](https://github.com/Dart-Code/Dart-Code/issues/2543). 🤔

**Comment by Ruzo** [comment] 2021-12-09 14:06
> > @Hacker437 I use it like this:
> > ```
> > dependencies:
> >   auto_route: ^3.1.3
> > 
> > dependency_overrides:
> >   auto_route:
> >     git:
> >       url: git@github.com:biklas7/auto_route_library.git
> >       ref: chore/update-flutter-beta
> >       path: auto_route
> > 
> > dev_dependencies:
> >   auto_route_generator: ^3.1.0
> > ```
> 
> Interesting doesn't work for me.
> 
> ```
> git@github.com: Permission denied (publickey).
> fatal: Could not read from remote repository.
> ```
> 
> Any ideas how to fix that?

If you're trying to fix the stable 2.8 issue, it's a new one. There is a pull request waiting to be merged so the contributor made available an override to his repo:

```
dependency_overrides:
  auto_route:
    git:
      url: https://github.com/Agondev/auto_route_library
      path: auto_route
```

Sorry, don't remember the thread id.

**Comment by biklas7** [comment] 2021-12-15 11:42
Version 3.2.0 seems to solve this 🎉

**Comment by n-anhtu0101** [comment] 2021-12-20 12:44
I still fold the above case

**Comment by n-anhtu0101** [comment] 2021-12-20 12:44
> Version 3.2.0 seems to solve this 🎉

I still fold the above case

**Comment by dgaedcke** [comment] 2022-01-11 21:06
> Version 3.2.0 seems to solve this

it seems there are 5 downvotes on this claim ... and my team is one of them

Does anyone else have suggestions??

**Comment by guyluz11** [comment] 2022-01-12 07:09
@dgaedcke 
> Does anyone else have suggestions??

Didn't try but I saw someone said that it worked after updating flutter version.


> I was having the same issues from autoroute updating my flutter version solved the problem for me.

You're welcome to try it out and share with us the results, and don't forget to mention your Flutter version.

**Comment by giiyms** [comment] 2022-01-12 07:10
Updating to latest version solved it for me to.

**Comment by ehagerty** [comment] 2022-01-13 18:05
I can confirm that using an M1 mac with a fresh set of tools, flutter 2.8.1, dart 1.15.1 and changing auto_route in your pubspec.yaml to exactly ^3.2.0 I'm able to build web, macos and ios successfully.  thank you!

**Comment by patonoide** [comment] 2022-02-23 03:21
Running ^3.2.0 with dart 2.10.2 fixes the issue for me.

**Comment by zs-dima** [comment] 2022-07-18 09:28
@github-actions

**Closed** 2022-09-24 08:22 UTC
Labels: no-issue-activity
