### ISSUE TITLE
Can not swipe back on iOS when using nested navigation

### ISSUE THREAD

**Issue by jtdLab** [Milad-Akarie/auto_route_library#1932] opened 2024-04-18 17:31 UTC
Is it possible to configure auto_route to allow dismissing parent via iOS back swipe if there is only 1 page on the nested navigation stack.

```dart
  AutoRoute(
    path: '/',
    page: PageARoute.page,
  ),
  AutoRoute(
    path: '/a',
    page: ShellARoute.page,
    children: [
      AutoRoute(
        path: '',
        page: PageAARoute.page,
      ),
      AutoRoute(
        path: 'b',
        page: PageABRoute.page,
      ),
    ],
  ),
```

e.g when stack is PageA, ShellA --- PageAA meaning PageAA is currently shown. Is it possible to make auto_route detect that ShellAs stack only contains 1 route and allow pop PageAA and the ShellA (similar to `context.maybePop()`) via back swipe?

Currently to achieve that the sub pages can be popped via swipe the router setup has to be changed to:

```dart
  AutoRoute(
    path: '/',
    page: PageARoute.page,
  ),
 AutoRoute(
        path: '/a',
        page: PageAARoute.page,
      ),
AutoRoute(
   path: '/a/b',
   page: PageABRoute.page,
),
```

**Comment by Milad-Akarie** [comment] 2024-04-21 07:54
@jtdLab this issue was fixed in 8.0.1, are you sure you're on the latest version?

**Comment by Milad-Akarie** [comment] 2024-04-22 07:32
@jtdLab there was a related issue to back-gestures, please check if you still have the problem in 8.1.1

**Comment by jtdLab** [comment] 2024-04-22 18:28
@Milad-Akarie Hey, thanks for the quick response :) Sadly i am still running into the problem. Can you check the sample at https://github.com/jtdLab/ios_nested_swipe to make sure we are on the same page.

**Comment by Milad-Akarie** [comment] 2024-04-23 07:42
@jtdLab Thanks for providing the sample repo, it was fixed by this PR #1940 in version 8.1.2
please confirm and close

**Comment by jtdLab** [comment] 2024-04-23 09:01
@Milad-Akarie Checked it and it now allows to pop the shell via swipe. However the swipe dismisses the shell route no matter how many child routes are on its stack (see updated sample) i think it would be good to align behavior with `context.maybePop()` and pop child pages (if there are more than 1) and else the shell. Or at least allow to configure that popping behavior.

**Comment by iagoandrei** [comment] 2024-04-23 18:23
@jtdLab Hello. Check if this PR corrects the situation described. https://github.com/Milad-Akarie/auto_route_library/pull/1941

**Comment by Milad-Akarie** [comment] 2024-04-26 08:01
@jtdLab Check latest release

**Comment by jtdLab** [comment] 2024-04-26 10:01
@Milad-Akarie is it on pub.dev?

**Comment by Milad-Akarie** [comment] 2024-04-26 10:03
I left in a hurry, I must've forgotten to confirm the upload

**Comment by jtdLab** [comment] 2024-04-27 15:10
Works 👍

**Closed** 2024-04-27 15:10 UTC

**Comment by nausharipov** [comment] 2024-11-22 12:57
The issue is present in the current version [9.2.2](https://pub.dev/packages/auto_route/versions/9.2.2): https://github.com/Milad-Akarie/auto_route_library/issues/2092
