### ISSUE TITLE
`TransitionsBuilders.noTransition` does not transition instantly

### ISSUE THREAD

**Issue by cekpowell** [Milad-Akarie/auto_route_library#1060] opened 2022-05-10 14:53 UTC
Here is a demonstration of what happens when a route is pushed using `TransitionBuilders.slideRight`:

https://user-images.githubusercontent.com/60888912/167692665-3d971abc-e425-4914-98fc-493775e6fe5a.mov

This shows that, when pushing a new route, the new route appears in front of the old route until the new route's entry animation has finished. Furthermore, when popping the new route, the new route will appear in front of the old route until the exit animation finishes. This behaviour makes sense.

Now, we can look at what happens when we use `TransitionBuilders.noTransition`:

https://user-images.githubusercontent.com/60888912/167692779-db9c4b75-2f7e-46fa-998e-dae0725b52a8.mov

Now, the new route appears instantly in-front of the old route when being pushed, but when being popped, there is a short delay before the new route is actually popped.

This is better observed when the new route being pushed doesnt take up the entire screen:

https://user-images.githubusercontent.com/60888912/167693411-6593b340-8040-40d0-b01c-4a33faa48d14.mov

So, when using `TransitionsBuilders.noTransition,` even though there is no animation between the two sub-routes, the sub-route stays on the screen until the animation time has elapsed remains. This creates a 'lag' effect, where the route being popped stays present on the screen for a short time after being popped. It is effectively waiting for the animation to complete, but as there is no animation so it just stays on the screen for the length of time defined by the animation.

So, I think the solution is for the animation within `TransitionsBuilders.noTransition` to have its duration set to 0, instead of just doing nothing which is what it currently does? Or perhaps, defining a custom transition with a duration of 0 is a better solution, but I am not sure how this can be done either.

**Comment by cekpowell** [comment] 2022-05-10 17:40
After playing round some more, I think I have found the issue but I am still not sure how to fix it.

By adding animation to my sub-routes using `CustomRoute` and `transitionsBuilder`, I get this behaviour:

https://user-images.githubusercontent.com/60888912/167688718-b625dc9c-9c22-47c2-beaa-e9c3cf780607.mov

This shows that, when pushing a new sub-route, the new sub-route appears in front of the old sub-route until the new sub-route's entry animation has finished. Furthermore, when popping the new sub-route, the new sub-route will appear in front of the old sub-route until the exit animation finishes.

So, when using `TransitionsBuilders.noTransition`, even though there is no animation between the two sub-routes, this behaviour of the sub-route staying on the screen until the animation time has elapsed remains. This creates the 'lag' effect I was seeing in the first example, where the sub-route being popped stays present on the screen for a short time after being popped.

So, I think a possible solution to the problem would be to force the page routing animation time to be zero. But I am not sure how this can be done? Maybe a custom animation could be defined with a timing of zero?

**Comment by Milad-Akarie** [comment] 2022-05-10 18:50
@cekpowell  Thank you for the nice explanation. 
This delay is caused by the reverse animation default duration (300 millis), to get rid of it simply set 
`reverseDurationInMilliseconds`  to zero inside of `CustomRoute` and if you're using `CustomAutoRouter` please wait until next build because I just found out that the global property is not getting generated .

closing this for now.

**Closed by Milad-Akarie** 2022-05-10 18:50 UTC
