### ISSUE TITLE
Assertion failing for beta.5+1

### ISSUE THREAD

**Issue by oliverfunk** [Milad-Akarie/auto_route_library#304] opened 2020-12-28 08:42 UTC
Not sure how I am the only one getting this error, but this assertion is failing after I import `package:auto_route/auto_route.dart`:

```
../../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/auto_route-1.0.0-beta.5+1/lib/src/router/auto_route_page.dart:72:16: Error: Getter not found: 'opaque'.
        assert(opaque),                                                 
               ^^^^^^                                                   
../../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/auto_route-1.0.0-beta.5+1/lib/src/router/auto_route_page.dart:134:16: Error: Getter not found: 'opaque'.
        assert(opaque), 
```

I downgraded to beta.4 and it's fine.

**Comment by Milad-Akarie** [comment] 2020-12-28 18:07
Hey @oliverfunk  I can't reproduce this error.
my env
Flutter (Channel stable, 1.22.5)
auto_route: 1.0.0-beta.5+1
auto_route_generator: 1.0.0-beta.5

I'll remove the assertion in the next build anyways.

**Comment by ramesbury** [comment] 2020-12-28 21:43
I am seeing this on beta:
```flutter --version   
Waiting for another flutter command to release the startup lock...
Flutter 1.25.0-8.1.pre • channel beta • https://github.com/flutter/flutter.git
Framework • revision 8f89f6505b (13 days ago) • 2020-12-15 15:07:52 -0800
Engine • revision 92ae191c17
Tools • Dart 2.12.0 (build 2.12.0-133.2.beta)
```

auto_route: 1.0.0-beta.5+1
auto_route_generator: 1.0.0-beta.5

**Comment by oliverfunk** [comment] 2020-12-28 22:37
Yeh I'm on beta.

flutter doctor -v:
```
[✓] Flutter (Channel beta, 1.25.0-8.1.pre, on Linux, locale en_ZA.UTF-8)
    • Flutter version 1.25.0-8.1.pre at /home/oliver/snap/flutter/common/flutter
    • Framework revision 8f89f6505b (13 days ago), 2020-12-15 15:07:52 -0800
    • Engine revision 92ae191c17
    • Dart version 2.12.0 (build 2.12.0-133.2.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /home/oliver/Android/Sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /usr/local/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.
```

**Comment by srcnysf** [comment] 2020-12-31 12:47
master too.

btw does that supports for flutter desktop apps ?

**Comment by rlee1990** [comment] 2020-12-31 14:47
I have the same issue on master

**Comment by Milad-Akarie** [comment] 2021-01-04 09:10
fixed in
 https://pub.dev/packages/auto_route/versions/1.0.0-beta.6
https://pub.dev/packages/auto_route_generator/versions/1.0.0-beta.6

**Closed by Milad-Akarie** 2021-01-04 09:10 UTC
