### ISSUE TITLE
Major problem in routing. Widgets are rebuilding/reconstructing every time!

### ISSUE THREAD

**Issue by m-zaink** [Milad-Akarie/auto_route_library#660] opened 2021-08-20 13:06 UTC
## Major problem in routing. Widgets are rebuilding/reconstructing when they shouldn't!
I have a set up as follows:

```dart
@MaterialAutoRouter(
  replaceInRouteName: 'View,Route',
  routes: <AutoRoute>[
    CustomRoute(
      page: HomeView,
      initial: true,
    ),
    CustomRoute(
      page: ChannelsView,
      transitionsBuilder: TransitionsBuilders.slideLeft,
    ),
    CustomRoute(
      page: AutoRouteView,
      transitionsBuilder: TransitionsBuilders.slideLeft,
    ),
  ],
)
class $AppRouter {}
```

```dart
class AutoRouteApp extends StatelessWidget {
  AutoRouteApp({Key? key}) : super(key: key);
  final _appRouter = AppRouter();

  @override
  Widget build(BuildContext context) {
    return MaterialApp.router(
      routerDelegate: AutoRouterDelegate(
        _appRouter,
      ),
      routeInformationParser: _appRouter.defaultRouteParser(),
    );
  }
}
```

```dart

class HomeView extends StatelessWidget {
  HomeView({Key? key}) : super(key: key) {
    print('HomeView.constructor');
  }

  @override
  Widget build(BuildContext context) => Scaffold(
        appBar: AppBar(
          title: Text('HomeView'),
        ),
        floatingActionButton: FloatingActionButton(
          child: Icon(Icons.arrow_forward),
          onPressed: () {
            context.router.push(ChannelsRoute()); // This is problematic
          },
        ),
      );
}
```

## What is the issue?

Everytime I'm pushing/popping the `ChannelsRoute()` (or any other route for that matter) from `HomeView`, `HomeView` constructor gets called again! That's so very very very wrong!

The same isn't happening when I push `ChannelsView()` using `Navigator.push(context, MaterialPageRoute(builder: (context) => ChannelsView());`.

Why this behavior? Is it even correct?

**Comment by m-zaink** [comment] 2021-08-21 04:39
@Milad-Akarie 
Can you please look into this ASAP?
This is a huge issue. Multiple calls to `build` method is acceptable. But entire widget objects being destroyed and recreated? That's very very unusual.

**Comment by BenevidesLecontes** [comment] 2021-08-21 21:48
@m-zaink I'm having this problem too.

**Comment by m-zaink** [comment] 2021-08-22 01:37
@Milad-Akarie 
This happens even when I use `AutoRoute` instead of `CustomRoute`.

Please fix this ASAP. It's a very critical issues.

**Comment by Milad-Akarie** [comment] 2021-08-22 10:34
@m-zaink @BenevidesLecontes reconstructing and rebuilding widgets in flutter is a very cheap task, because widgets aren't the actual render tree they just configure it with that being said, there shouldn't be any state inside of a `StatelessWidget.
`StatefulWidgets` on the other hand maintain their states as expected.   

in Navigator 2.0 pages are passed as a stack of widgets ( every time the parent widget rebuilds). 
if you're still not convinced change your `HomeView` into a `StatefulWidget` then change the initial state before you navigate to the next screen and back then see if the state changes back to the initial state.

**Comment by m-zaink** [comment] 2021-08-22 10:42
In the above example, there is no state in any of widgets I'm using.

And yet HomeView's constructor gets called again and again.

Is it normal?

And why doesn't it happen when I do push using the default navigator?


Rebuilds are acceptable. But entire widget objects being destroyed and created? That's something I'm seeing for the first time.

**Comment by BenevidesLecontes** [comment] 2021-08-22 11:10
@Milad-Akarie for me, my initState methods are being called again in statefullWidgets

**Comment by Milad-Akarie** [comment] 2021-08-22 11:54
@m-zaink as I said, Native Navigator 2.0 does things differently

**Comment by Milad-Akarie** [comment] 2021-08-22 11:54
@BenevidesLecontes where are you creating your AppRouter instance?

**Comment by BenevidesLecontes** [comment] 2021-08-22 12:34
@Milad-Akarie yes, in the app widget

**Comment by Milad-Akarie** [comment] 2021-08-22 12:35
@BenevidesLecontes inside of the build method? 
please share your App widget

**Comment by BenevidesLecontes** [comment] 2021-08-22 13:01
@Milad-Akarie  my build method, im using `ExtendedNavigator.createInstance()` to create the instance:
```
@override
  Widget build(BuildContext context) {
    return LayoutBuilder(
      builder: (context, constraints) {
        return OrientationBuilder(
          builder: (context, orientation) {
            SizeConfig(
              designScreenWidth: 360,
              designScreenHeight: 640,
            ).init(constraints, orientation);
            ExtendedNavigator.createInstance();
            return MaterialApp.router(
              theme: themeCreate(context),
              debugShowCheckedModeBanner: false,
              routerDelegate: _router.delegate(
                navigatorObservers: () => [
                  FirebaseAnalyticsObserver(analytics: analytics),
                  AutoRouteObserver(),
                ],
                initialRoutes: [
                  _initialRoutes,
                ],
              ),
              routeInformationParser: _router.defaultRouteParser(
                includePrefixMatches: true,
              ),
              localizationsDelegates: [
                GlobalCupertinoLocalizations.delegate,
                GlobalWidgetsLocalizations.delegate,
                GlobalMaterialLocalizations.delegate
              ],
              supportedLocales: [
                const Locale('pt'),
              ],
              builder: (context, extendedNav) {
                return extendedNav!;
              },
            );
          },
        );
      },
    );
```
```
static late AppRouter _router;
  static void createInstance() {
     _router = AppRouter();
  }
```

**Comment by Milad-Akarie** [comment] 2021-08-22 13:08
@BenevidesLecontes Where's the _router coming from?

**Comment by BenevidesLecontes** [comment] 2021-08-22 13:10
@Milad-Akarie _router is getter
`AppRouter get _router => ExtendedNavigator.router;`

**Comment by Milad-Akarie** [comment] 2021-08-22 13:19
@BenevidesLecontes You're creating a new instance of AppRouter every time your widget rebuilds! 

maybe your `ExtendedNavigator` should look something like this
```dart
class ExtendedNavigator {
  final static late AppRouter router;
}
```

**Comment by BenevidesLecontes** [comment] 2021-08-22 13:21
I already did a singleton of appRouter, same result.

**Comment by Milad-Akarie** [comment] 2021-08-22 13:24
@BenevidesLecontes calling this line ` ExtendedNavigator.createInstance();` will create a new instance every time

**Comment by BenevidesLecontes** [comment] 2021-08-22 13:28
@Milad-Akarie i did what you suggest and tried a singleton way. Same thing

**Comment by Milad-Akarie** [comment] 2021-08-22 13:35
@BenevidesLecontes could you create a small gist with test pages so I can clone it on my machine?

**Comment by BenevidesLecontes** [comment] 2021-08-22 14:00
@Milad-Akarie I'll try to create something to be able to reproduce. Thanks

**Comment by BenevidesLecontes** [comment] 2021-08-25 15:00
@Milad-Akarie I found the issue, I don't know why, when i do this my statefullWidgets are rebuilded when I pop
```
class Test extends StatefulWidget implements AutoRouteWrapper {
          @override
         Widget wrappedRoute(BuildContext context) => PageContainer(
            pageType: PageType.InvestmentStatement,
            child: this,
      );
}
```
If remove the AutoWrapper and use the widget PageContainer on the build method, it works fine.
PS: The issue occur when i do some `flutter bloc action` and then `pop`

**Comment by DFelten** [comment] 2021-09-09 09:27
Same issue here. The build methods of all widgets are triggered each time a new route is opened. Unfortunately the project is too large to share. I will try to create a small example to show this problem.

**Comment by RicardoLimaDev** [comment] 2021-09-09 13:16
Same problem here.

**Comment by bounty1342** [comment] 2021-09-12 13:09
As I said on the discord :
AutoRouter :
![](https://cdn.discordapp.com/attachments/821361382188253224/885181653822079076/unknown.png)
Navigator:
![](https://cdn.discordapp.com/attachments/821361382188253224/885184846966685777/unknown.png)

Seems only Inherited Widget are impacted (Not All), and it might be related to :
https://stackoverflow.com/questions/66842962/flutter-page-with-singletickerproviderstatemixin-cause-unnecessary-build/66897710#66897710

Those tabBar, animationControler have a Vsync and use a Ticker and are probably impacted...

The weird part is that Navigator doesn't seem to have this behavior.

**Comment by Milad-Akarie** [comment] 2021-09-19 19:40
@bounty1342 this should be fixed in the latest release, you can now read or watch routers and only rebuild widgets that watch the router for changes.

@m-zaink

**Closed** 2021-09-19 19:40 UTC
