### ISSUE TITLE
Can't pass physics to AutoTabsRouter.tabBar and pageView

### ISSUE THREAD

**Issue by hawkkiller** [Milad-Akarie/auto_route_library#1117] opened 2022-06-19 15:28 UTC
I need an opportunity to pass the scroll physics because it is uncontrollable now.

**Comment by hawkkiller** [comment] 2022-06-19 15:31
https://github.com/Milad-Akarie/auto_route_library/pull/1118

**Comment by kishan-dhankecha** [comment] 2022-06-22 12:35
You should check the available issues before opening the new one, that way you can check if there is a solution available already or some other useful information regarding the issue as well.

Duplicate of #1109

**Comment by hawkkiller** [comment] 2022-06-23 19:24
@kishan-dhankecha the author doesnt support the package at all

**Closed** 2022-06-28 11:27 UTC
