### ISSUE TITLE
Disable preserving state

### ISSUE THREAD

**Issue by steve-cahn** [Milad-Akarie/auto_route_library#505] opened 2021-04-30 23:27 UTC
How can I not preserve the state/page when using `bottomNavigationBuilder`? After I navigate to another tab, then go back to the original one, the state and everything about it is the same, as if I never left it. How can I make the page reload itself when the tab goes to that page?

**Comment by theweiweiway** [comment] 2021-04-30 23:34
```   
 AutoTabsScaffold(lazyLoad: false,)   
```

**Comment by steve-cahn** [comment] 2021-05-01 00:25
It's not working... When I go to a nested route, change the tab, then change it back to the original one, I'm still seeing a nested route...

**Comment by bogdanmarinescu** [comment] 2021-05-03 15:07
this is not a bug,  this should be marked as a feature.

**Comment by theweiweiway** [comment] 2021-05-03 15:24
@bogdanmarinescu It's a bug because the feature is implemented but not working as intended

**Comment by bogdanmarinescu** [comment] 2021-05-03 15:36
> @bogdanmarinescu It's a bug because the feature is implemented but not working as intended

What is the intended behavior? If I move from one BottomNavigationBarItem to another the previous tab should get disposed?

**Comment by theweiweiway** [comment] 2021-05-03 15:39
I see - sorry i misunderstood the question, 

The `lazyload` is only for the initial load. Not switching back and forth between tabs and disposing the tab when exited. Yes, it is a feature

**Comment by mikepyts** [comment] 2021-05-07 15:53
One of the cases needed for me is that I am loading useful information each time in initState() of the selected tab route page, but with the preserved state, I need to move this into another place, bottom tab navigation bar etc.

**Comment by Milad-Akarie** [comment] 2021-05-07 15:58
@mikepyts  seems to me you just want to notify your tab overtime it's re-selected is that correct?

**Comment by Milad-Akarie** [comment] 2021-05-07 18:10
The whole idea of tabs router is to maintain state in parallel, if you don't want to preserve your state for any of your tabs just useqn AutoRouter() instead and call router.replace in onTabSelected

**Comment by mikepyts** [comment] 2021-05-07 18:22
@Milad-Akarie sorry for misunderstanding, just gave an example in which situations do we use that, of course replacing AutoRoute in tab selection is a possible way, this is all about improvements instead of workarounds and new features. I have found this issue because had the same situation and documentation doesn't cover such situations

**Comment by Milad-Akarie** [comment] 2021-05-07 19:07
@mikepyts I understand, If i'm to do something on my site it's gonna be a flag that disables state preserving for all tabs which I don't think is a wanted behavior but it's still doable. on the other hand you users can simply disable state preserving for certain routes by assigning a simple key 

```dart
class MyStatefulTabPage extends StatefulWidget {
  MyStatefulTabPage() : super(key: UniqueKey());
....
}
```
MyStatefulTabPage will be rebuilt everytime it's selected.
if you guys wanna go with an overall flag just let me know.

**Comment by steve-cahn** [comment] 2021-05-16 20:48
@Milad-Akarie  Yes, I think it's nice to have that option of having an overall flag

**Comment by olegys** [comment] 2021-11-26 14:46
> @mikepyts I understand, If i'm to do something on my side it's gonna be a flag that disables state preserving for all tabs which I don't think is a wanted behavior but it's still doable. on the other hand you users can simply disable state preserving for certain routes by assigning a simple key

This solution dont work...

**Comment by Maadhav** [comment] 2021-12-24 17:44
#847 This seems to be a fix for the persistence problem

**Comment by breucode** [comment] 2022-05-07 14:03
> @mikepyts I understand, If i'm to do something on my side it's gonna be a flag that disables state preserving for all tabs which I don't think is a wanted behavior but it's still doable. on the other hand you users can simply disable state preserving for certain routes by assigning a simple key
> 
> ```dart
> class MyStatefulTabPage extends StatefulWidget {
>   MyStatefulTabPage() : super(key: UniqueKey());
> ....
> }
> ```
> 
> MyStatefulTabPage will be rebuilt everytime it's selected. if you guys wanna go with an overall flag just let me know.

Unfortunately, this does not work for me. I have a Stateful Widget, with a unique key, but the state is never updated.

**Closed** 2022-07-15 08:22 UTC
Labels: enhancement, no-issue-activity
