### ISSUE TITLE
Replacing nested path

### ISSUE THREAD

**Issue by mrruby** [Milad-Akarie/auto_route_library#172] opened 2020-07-20 20:21 UTC
Hi I have such a nested route:

```
@MaterialAutoRouter(routes: [
  MaterialRoute(page: Splash, initial: true),
  MaterialRoute(page: HomePage),
  MaterialRoute(
    page: SignInScreen,
    children: <AutoRoute>[
      MaterialRoute(path: '/', page: SignInMethod),
      MaterialRoute(page: SignInByEmail),
    ],
  )
])
```

Hi can I replace nested route with one from the root?

When I'm doing `context.rootNavigator.replace(Routes.homePage);`

I'm getting

```
════════ Exception caught by widgets library ═══════════════════════════════════
The following assertion was thrown while finalizing the widget tree:
Looking up a deactivated widget's ancestor is unsafe.

At this point the state of the widget's element tree is no longer stable.

To safely refer to a widget's ancestor in its dispose() method, save a reference to the ancestor by calling dependOnInheritedWidgetOfExactType() in the widget's didChangeDependencies() method.
```

**Comment by Milad-Akarie** [comment] 2020-07-21 09:55
@mrruby Where are yo calling the replace method?

**Comment by mrruby** [comment] 2020-07-21 09:59
In Bloc Listener of the nested route Screen

**Comment by mrruby** [comment] 2020-07-21 10:15
Every hot reloads on this nested route gives mi also:

```
The following assertion was thrown while finalizing the widget tree:
Looking up a deactivated widget's ancestor is unsafe.
At this point the state of the widget's element tree is no longer stable.
To safely refer to a widget's ancestor in its dispose() method, save a reference to the ancestor by
calling dependOnInheritedWidgetOfExactType() in the widget's didChangeDependencies() method.
When the exception was thrown, this was the stack:
#0      Element._debugCheckStateIsActiveForAncestorLookup.<anonymous closure> 
package:flutter/…/widgets/framework.dart:3836
#1      Element._debugCheckStateIsActiveForAncestorLookup 
package:flutter/…/widgets/framework.dart:3850
#2      Element.dependOnInheritedWidgetOfExactType 
package:flutter/…/widgets/framework.dart:3892
#3      ModalRoute.of 
package:flutter/…/widgets/routes.dart:882
#4      ParentRouteData.of 
package:auto_route/src/route_data.dart:86
#5      ExtendedNavigatorState.routerName 
package:auto_route/src/extended_navigator.dart:496
#6      ExtendedNavigatorState.dispose 
```

**Comment by Milad-Akarie** [comment] 2020-07-21 10:33
Regarding hot reload issue, it was reported and I  just pushed a fix
```
 auto_route: 0.6.6
auto_route_generator: 0.6.6
```
I think your first issue is caused by you trying to look up the widgets tree when a widget is building or being disposed.
Could you use ExtendedNavigator without context to confirm this?
`ExtendedNavigator.root.replace(Routes.homePage);`

**Comment by mrruby** [comment] 2020-07-21 10:59
The Hot reload issue is fixed indeed.

But the error when switching routes still occurs, even when `ExtendedNavigator.root.replace(Routes.homePage);` is used

```
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following assertion was thrown while finalizing the widget tree:
Looking up a deactivated widget's ancestor is unsafe.
At this point the state of the widget's element tree is no longer stable.
To safely refer to a widget's ancestor in its dispose() method, save a reference to the ancestor by
calling dependOnInheritedWidgetOfExactType() in the widget's didChangeDependencies() method.
When the exception was thrown, this was the stack:
#0      Element._debugCheckStateIsActiveForAncestorLookup.<anonymous closure> 
package:flutter/…/widgets/framework.dart:3836
#1      _Closure.call (dart:core-patch/function.dart)
#2      Element._debugCheckStateIsActiveForAncestorLookup 
package:flutter/…/widgets/framework.dart:3850
#3      Element.dependOnInheritedWidgetOfExactType 
package:flutter/…/widgets/framework.dart:3892
#4      ModalRoute.of 
package:flutter/…/widgets/routes.dart:882
#5      ParentRouteData.of 
package:auto_route/src/route_data.dart:86
#6      ExtendedNavigatorState.routerName 
package:auto_route/src/extended_navigator.dart:477
#7      ExtendedNavigatorState.dispose 
package:auto_route/src/extended_navigator.dart:467
 
```

**Comment by dannnnthemannnn** [comment] 2020-08-12 02:10
I am having the exact same issue. 

The reason I am doing this is I have two outer pages. I navigate to the inner route which has buttons to move between the inner route sections. However, clicking the global back button should go to the homepage using the root navigator, not the nested one. I am replacing because if I navigate to this route directly, then I cannot pop as the homepage is not under this route.

**Comment by AnggaSP** [comment] 2020-11-27 21:13
@Milad-Akarie Any update on this? We are also using nested router and use BlocListener to navigate based on whether the state is successful or not and the error came up regardless if we use context or ExtendedNavigator directly.

**Comment by theweiweiway** [comment] 2021-04-14 04:43
Is this still an issue in 1.0.2?

**Comment by Milad-Akarie** [comment] 2021-04-15 10:59
@theweiweiway  I believe this has to do with legacy navigator which is no longer supported so I'm closing this.

**Closed by Milad-Akarie** 2021-04-15 10:59 UTC
