### ISSUE TITLE
How to navigate to particular tab manually?

### ISSUE THREAD

**Issue by Chojecki** [Milad-Akarie/auto_route_library#428] opened 2021-03-26 16:22 UTC
Is there a way to navigate to for example 2th tab by any other way than tapping the navigation item?

Use Case:
App has onboarding. After boarding I want to user to land at profile page which is 3th page of bottom navigation bar. Next time when user will open the app (after kill) I want him to land on first bottom navigation page.

**Comment by theweiweiway** [comment] 2021-03-26 16:31
@Chojecki  you should be able to call `tabsRouter.setActiveIndex` to programatically set the active index after a certain action.

Please see here for more details (bottom of page): https://autoroute.vercel.app/advanced/bottom_navigation_bar_routing

**Comment by Chojecki** [comment] 2021-03-26 16:33
It doesn't work. I mean the active tab is changing but the view stays on the first router

**Comment by Chojecki** [comment] 2021-03-26 16:50
Im using beta-10. We didn't migrated to flutter 2.0 yet. Maybe it's a bug of beta? Can someone confirm it is working at new stable version?

**Comment by theweiweiway** [comment] 2021-03-26 16:51
I see, can I see your router setup please?

**Comment by Chojecki** [comment] 2021-03-26 17:28
Sure

```dart

@MaterialAutoRouter(
  replaceInRouteName: 'Screen,Route',
  routes: <AutoRoute>[
    AutoRoute<dynamic>(
      path: '/',
      page: SplashScreen,
    ),
    AutoRoute<dynamic>(
        path: '/login', page: LoginScreen, fullscreenDialog: true),
    AutoRoute<dynamic>(path: '/welcome', page: WelcomeFormScreen),
    AutoRoute<dynamic>(path: '/onboarding', page: OnboardingScreen),
    AutoRoute<dynamic>(
        path: '/onboarding/filters', page: OnboardingPhotoFilters),
    RedirectRoute(path: '*', redirectTo: '/'),
    AdaptiveRoute<dynamic>(
      path: '/app',
      page: TabNavigation,
      usesTabsRouter: true,
      fullscreenDialog: true,
      children: [
        AutoRoute<dynamic>(
          path: 'home',
          name: 'HomeRouter',
          page: HeroEmptyRouterPage,
          children: [
            AutoRoute<dynamic>(path: '', page: HomeScreen),
            AdaptiveRoute<dynamic>(
                path: 'createPost',
                page: CreatePostScreen,
                fullscreenDialog: true),
            RedirectRoute(path: '*', redirectTo: ''),
          ],
        ),
        AutoRoute<dynamic>(
          path: 'notifications',
          name: 'NotificationsRouter',
          page: EmptyRouterPage,
          children: [
            AutoRoute<dynamic>(path: '', page: NotificationsScreen),
            RedirectRoute(path: '*', redirectTo: ''),
          ],
        ),
        AutoRoute<dynamic>(
          path: 'groups',
          name: 'GroupsRouter',
          page: EmptyRouterPage,
          children: [
            AutoRoute<dynamic>(path: '', page: GroupsScreen),
            RedirectRoute(path: '*', redirectTo: ''),
          ],
        ),
        AutoRoute<dynamic>(
          path: 'profile',
          name: 'ProfileRouter',
          page: EmptyRouterPage,
          children: [
            AutoRoute<dynamic>(path: '', page: MyProfileScreen),
            RedirectRoute(path: '*', redirectTo: ''),
          ],
        ),
        AutoRoute<dynamic>(
          path: 'additional',
          name: 'AdditionalMenuRouter',
          page: EmptyRouterPage,
          children: [
            AutoRoute<dynamic>(path: '', page: AdditionalMenuScreen),
            RedirectRoute(path: '*', redirectTo: ''),
          ],
        )
      ],
    ),
  ],
)
class $Router {}

/// This [HeroEmptyRouterPage] is needed for [Hero] transition in nested navigation.
/// Not  related to [AutoRouter] because [HeroController] is maintained inside the MaterialApp
class HeroEmptyRouterPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return HeroControllerScope(
      controller: HeroController(),
      child: const AutoRouter(),
    );
  }
}

```

**Comment by theweiweiway** [comment] 2021-03-26 17:31
Hey, can I see your `OnboardingScreen` - I'm assuming you are. using `AutoRouter.declarative` here? How exactly is that flow ended, and then how exactly do you try to push to the 3rd tab route?

**Comment by Chojecki** [comment] 2021-03-26 18:01
No, we are not using AutoRouter.declarative yet (we refactored from navigator 1.0). We just call:
`AutoRouter.of(context).navigate(const TabNavigation(fromOnboaring: true));` at the end of onboarding.

So to TabNavigation looks like this: 
```dart

class TabNavigation extends StatelessWidget {
  const TabNavigation({Key key, this.fromOnboarding = false}) : super(key: key);

final bool fromOnboarding;

  @override
  Widget build(BuildContext context) {
    return WillPopScope(
      onWillPop: () async => false,
      child: Scaffold(
        body: AutoTabsRouter(
          routes: const [
            HomeRouter(),
            NotificationsRouter(),
            GroupsRouter(),
            ProfileRouter(),
            AdditionalMenuRouter()
          ],
          duration: const Duration(milliseconds: 400),
          builder: (context, child, animation) {
            final tabsRouter = context.tabsRouter;
            return Scaffold(
              body: FadeTransition(
                opacity: animation,
                child: child,
              ),
              bottomNavigationBar: buildBottomNavigationBar(tabsRouter, fromOnboarding),
            );
          },
        ),
      ),
    );
  }
}

BottomNavigationBar buildBottomNavigationBar(TabsRouter tabsRouter, bool fromOnboarding) {

if(fromOnboarding){
tabsRouter.setActiveIndex(3);
}

  return BottomNavigationBar(
    onTap: (index) => tabsRouter.setActiveIndex(index),
    currentIndex: tabsRouter.activeIndex,
    items: const [
      BottomNavigationBarItem(
        icon: Icon(Icons.home),
        label: 'Home',
      ),
      BottomNavigationBarItem(
        icon: Icon(Icons.home),
        label: 'Feed',
      ),
      BottomNavigationBarItem(
        icon: Icon(Icons.home),
        label: 'Spots',
      ),
      BottomNavigationBarItem(
        icon: Icon(Icons.home),
        label: 'Spots',
      ),
      BottomNavigationBarItem(
        icon: Icon(Icons.home),
        label: 'Spots',
      ),
    ],
  );
}

```

So TabNavigation has a flag if it comes from onboarding or not. If yes, then we try to setActiveIndex to 3 - which is profile screen.

**Comment by theweiweiway** [comment] 2021-04-04 05:47
Could it be that your TabNavigation page is not called TabNavigationScreen? If you call it that, you can push TabNavigationRoute 

Also, it's good practice to rename all of your pages in the router setup to end with the word "Screen", so that auto route can generate the same page but ending in "Route".  Otherwise, it might be hard to push certain types

**Comment by Chojecki** [comment] 2021-04-04 08:29
@theweiweiway I think its more about how to dynamically set tab index during push of router with tab navigation. For now we made a Hack with setting a global flag of 'comesFromOnbarding' and we are checking this flag on init of Screen under tab of index 1. So if flag is true we are doing "setActiveIndex" on 3. So it works after TabNavigationScreen already rendered at least one page, but originally we wanded to push TabNavScreen with parameters of initial index, but it doesn't work then

**Comment by Milad-Akarie** [comment] 2021-04-04 09:16
@Chojecki  sorry for the delay, I believe what you need can be achieved by simply setting an initial child

`AutoRouter.of(context).navigate(const TabNavigation(children: [GroupsRouter()]));`

**Comment by Chojecki** [comment] 2021-04-04 09:25
@Milad-Akarie no worries. Thanks for response. Will try

**Comment by Chojecki** [comment] 2021-04-04 09:46
@Milad-Akarie This make sense, but with your apporach the screen of index 3 (of original tabnavigatror) will have an index 1 then - so will be under different icon at tapbar if that make sense

**Comment by Milad-Akarie** [comment] 2021-04-04 09:54
@Chojecki have you tried it? the intended behavior should override the corresponding index with the passed child, it should not reorder the declared routes or anything, if it does then it's a bug.

**Comment by Chojecki** [comment] 2021-04-04 09:56
@Milad-Akarie no I didn't. It was just my assumption. Probably I should check it before comment here, so apologize. Will try when back home

**Comment by Milad-Akarie** [comment] 2021-04-04 09:58
@Chojecki oh take your time, let me know if it works as you'd expect.

**Comment by Chojecki** [comment] 2021-04-04 11:41
@Milad-Akarie you solution works. Thanks for advice. The only thing I had to change was a list of routers passed into `AutoTabsRouter` as mutable list (so TabNavigation as StatefullWidget). Happy to close this issue.

One thing - maybe a good idea to update the docs with this explanation. Happy to help you with that if possible. When I told my friend about this solution - his first question was the same like mine (will other tabs work then?)

**Comment by Milad-Akarie** [comment] 2021-04-04 11:53
@Chojecki glad to hear that, I guess you could open a PR.
closing this for now.

**Closed by Milad-Akarie** 2021-04-04 11:53 UTC

**Comment by theweiweiway** [comment] 2021-04-04 14:03
whoops i can't believe i didn't figure this out..

@Chojecki hey if you had any improvements for the docs I'd be happy to take a look at it - you could message me here or make a PR

**Comment by edwardfhsiao** [comment] 2021-07-23 07:29
@Milad-Akarie @theweiweiway Hi, thank you for your explanations.

But I still have 2 questions that might need your help.

1, What if I need to manually set my initial tab to the second tab(ProfileRouter) on the home screen (assuming we have three tabs at the bottom), where is the best place to trigger ```  context.navigateTo(HomeRouter(children: [SecondRoute()]));```, or does it have another way to do so?

2, What if I need to pass a param to ```HomePage``` like ```myParam``` in the example, where do I pass it? Because I guess it is not possible to register it in the router like this:
```dart
AutoRoute(
      path: '/',
      name: 'HomeRouter',
      page: HomePage(myParam: 1),
      ...
```

```dart
// home.dart

class HomePage extends StatefulWidget {
  final String myParam;
  const HomePage({Key? key, required this.myParam}) : super(key: key);
  ...
}

class _HomeState extends State<HomePage> {
  @override
  Widget build(context) {

    // MY QUESTION 1
    context.navigateTo(HomeRouter(children: [ProfileRoute()]));
    // MY QUESTION 2
    print(widget.myParam);

    return AutoTabsScaffold(
      appBarBuilder: (_, tabsRouter) => AppBar(
        title: Text(context.topRoute.name),
        leading: AutoBackButton(),
      ),
      routes: [
        BooksRouter(),
        ProfileRouter(),
        SettingsRouter(tab: 'default'),
      ],
      bottomNavigationBuilder: buildBottomNav,
    );
  }

  BottomNavigationBar buildBottomNav(
    BuildContext context, TabsRouter tabsRouter) {
    return BottomNavigationBar(
      currentIndex: tabsRouter.activeIndex,
      onTap: (index) {
        if (tabsRouter.activeIndex == index) {
          tabsRouter.stackRouterOfIndex(index)?.popUntilRoot();
        } else {
          tabsRouter.setActiveIndex(index);
        }
      },
      items: [
        BottomNavigationBarItem(
          icon: Icon(Icons.source),
          label: 'Books',
        ),
        BottomNavigationBarItem(
          icon: Icon(Icons.person),
          label: 'Profile',
        ),
        BottomNavigationBarItem(
          icon: Icon(Icons.settings),
          label: 'Settings',
        ),
      ],
    );
  }
}
```

**Comment by agordeev** [comment] 2021-11-16 05:48
>@Chojecki sorry for the delay, I believe what you need can be achieved by simply setting an initial child
>
>```
>AutoRouter.of(context).navigate(const TabNavigation(children: [GroupsRouter()]));
>```
>
>this's like navigating to to '/app/groups' using paths

I must say that it's quite an unintuitive way to set an initial route by passing it as a single child in the `children` array of the tab route 😕

**Comment by Milad-Akarie** [comment] 2021-11-16 08:49
@agordeev agree, but StackRouters support passing multiple initial children, and they both use the same Route info model `PageRouteInfo`, do you have a better idea to handle this?

**Comment by dossanovruslan** [comment] 2023-01-23 06:44
> ```dart
>    usesTabsRouter: true,
>       fullscreenDialog: true,
> ```

tabsRouter.setActiveIndex(1, notify: false);

**Comment by dossanovruslan** [comment] 2023-01-23 06:45
tabsRouter.setActiveIndex(1, notify: false);
