### ISSUE TITLE
"PostRouteArgs can not be null because the corresponding page has a required parameter" as soon as I try to select a widget in WidgetInspector 

### ISSUE THREAD

**Issue by escamoteur** [Milad-Akarie/auto_route_library#1997] opened 2024-07-19 12:23 UTC
Hi.

we are using autoroute 8.3.0 and everytime I try to use the WidgtInspector I get this exception here:

```
ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Missing or invalid required parameter

PostRouteArgs can not be null because the corresponding page has a required parameter
#0      RouteData.argsAs (package:auto_route/src/route/route_data.dart:99:9)
#1      new $WcRouter.<anonymous closure> (package:watchcrunch/the_app/router/router.gr.dart:151:30)
#2      RootStackRouter._pageBuilder (package:auto_route/src/router/controller/root_stack_router.dart:161:20)
#3      StackRouter._addEntry (package:auto_route/src/router/controller/routing_controller.dart:1606:29)
#4      StackRouter._pushAllGuarded (package:auto_route/src/router/controller/routing_controller.dart:1581:29)
<asynchronous suspension>
```
any idea what we make wrong? when using the app the parameters are all passed as expected.

**Comment by Milad-Akarie** [comment] 2024-07-20 15:53
@escamoteur you just start the WidgetInspector to get this error?

**Comment by escamoteur** [comment] 2024-07-20 15:57
@Milad-Akarie I start it and the moment I activate the widget selector I get this exception

**Comment by escamoteur** [comment] 2024-07-20 15:57
If I can do anything to provide more data, please tell me

**Comment by Milad-Akarie** [comment] 2024-07-20 16:06
@escamoteur vs or Android studio?

**Comment by escamoteur** [comment] 2024-07-20 16:06
VS code

**Comment by Milad-Akarie** [comment] 2024-07-20 19:49
@escamoteur Unfortunately, I could not reproduce the error no matter what I did, tried on Android, IOS and web with no success, what do you suggest I do to encounter this error?

**Comment by escamoteur** [comment] 2024-07-20 19:52
I was fearing that. Our app is a pretty big Biest with complex nested navigation.
Any way I could add some additional logging?
Am 20. Juli 2024, 20:50 +0100 schrieb Milad Akarie ***@***.***>:

**Comment by Milad-Akarie** [comment] 2024-07-21 08:57
This is most likely a result of lost state, maybe you can check whether the router is re-initiated? 
and sure, let's see the logs.
also what platform are you working on?

**Comment by escamoteur** [comment] 2024-07-21 13:51
I just tested it again on Android and there is works so I only had this problem on Windows. 
Which also means it's not such a pressing issue

**Comment by Milad-Akarie** [comment] 2024-07-22 08:47
I'm closing this for now but let me know if you have clear steps to reproduce it.

**Closed by Milad-Akarie** 2024-07-22 08:47 UTC
