### ISSUE TITLE
!keyReservation.contains(key) assert fails when trying to push a different instance of a similar route over a current one in the stack.

### ISSUE THREAD

**Issue by NamanShergill** [Milad-Akarie/auto_route_library#492] opened 2021-04-28 04:53 UTC
Assert that is failing:  https://github.com/flutter/flutter/blob/aecd5e030220c622e21cc0a80f738cd0958c2865/packages/flutter/lib/src/widgets/navigator.dart#L3623

Tried using  `push`, `pushAll`, `navigate`, or `navigateAll`. Same results.

Error thrown when trying to go back when the assert fails:
```
A GlobalKey was used multiple times inside one widget's child list.

The offending GlobalKey was: [LabeledGlobalKey<NavigatorState>#1a692]
The parent of the widgets with that key was: AutoRouteNavigator
  state: _AutoRouteNavigatorState#92932
The first child to get instantiated with that key became: Navigator-[LabeledGlobalKey<NavigatorState>#1a692]
  dirty
  dependencies: [HeroControllerScope, StackRouterScope, UnmanagedRestorationScope]
  state: NavigatorState#13e5d(tickers: tracking 2 tickers)
The second child that was to be instantiated with that key was: AutoRouteNavigator
A GlobalKey can only be specified on one widget at a time in the widget tree.
```

Tested on the latest version, 2.0.1

**Comment by aarajput** [comment] 2021-04-28 08:26
I am also facing same issue.  This is how i am reproducing it.

1. Open 1st page on website (e.g /auth/login)
2. Now click on **Forgot Password** button (now its on /auth/forgot-password)
3. Now click back button of browser (now its back on /auth/login)
4. Now click **Forgot Password** button again. (now it shows this error)

**Note:** I am using _AutoRouter.of(context).replace(ForgotPasswordRoute())_ to navigate to Forgot Password screen.

**Comment by Milad-Akarie** [comment] 2021-04-28 11:32
I'll remove the limitation for one page (key) per stack in the next build as it seems to be causing alot of issues.

**Comment by aarajput** [comment] 2021-04-28 12:11
@Milad-Akarie ! Exact Issue is that, 
let say there is one page in stack **Forgot-Password-Page**, and i press back button on browser, then instead of removing **Forgot-Password-Page** from stack and adding **Login-Page** into the stack, it just added **Login-Page** in to the stack.

**Comment by Milad-Akarie** [comment] 2021-04-29 19:23
@aarajput yup that was a related issue but not the same, It should be fixed in auto_route 2.0.0
please confirm if it's fixed.

**Comment by Milad-Akarie** [comment] 2021-04-29 19:23
@NamanShergill should be fixed in auto_route 2.0.0 
please confirm and close.

**Comment by grappetite-ali** [comment] 2021-04-30 05:46
@Milad-Akarie ! This issue has been fixed. Thanks. You can close it now.

**Closed** 2021-04-30 05:48 UTC

**Comment by Chojecki** [comment] 2021-05-05 12:51
I still experience this issue in 2.0.2 @Milad-Akarie

**Comment by Milad-Akarie** [comment] 2021-05-05 13:04
@Chojecki what is the error you get?

**Comment by Chojecki** [comment] 2021-05-05 13:05
exactly the same as original author so

```
A GlobalKey was used multiple times inside one widget's child list.

The offending GlobalKey was: [LabeledGlobalKey<NavigatorState>#1a692]
The parent of the widgets with that key was: AutoRouteNavigator
  state: _AutoRouteNavigatorState#92932
The first child to get instantiated with that key became: Navigator-[LabeledGlobalKey<NavigatorState>#1a692]
  dirty
  dependencies: [HeroControllerScope, StackRouterScope, UnmanagedRestorationScope]
  state: NavigatorState#13e5d(tickers: tracking 2 tickers)
The second child that was to be instantiated with that key was: AutoRouteNavigator
A GlobalKey can only be specified on one widget at a time in the widget tree.
```

**Comment by Milad-Akarie** [comment] 2021-05-05 13:06
@Chojecki  do you get this? 
!keyReservation.contains(key) assert fails when trying to push a different instance of a similar route over a current one in the stack

**Comment by Chojecki** [comment] 2021-05-05 13:15
@Milad-Akarie oh I've noticed I have a firebase route observers and this causes issues. Weird as it throws this GlobalKey exceptions and error like

```
lutter: The following assertion was thrown building AutoRouteNavigator:
flutter: 'package:flutter/src/widgets/navigator.dart': Failed assertion: line 3364 pos 14:
flutter: 'observer.navigator == null': is not true.
flutter:
flutter: Either the assertion indicates an error in the framework itself, or we should provide substantially
flutter: more information in this error message to help you determine and fix the underlying cause.
flutter: In either case, please report this assertion by filing a bug on GitHub:
flutter:   https://github.com/flutter/flutter/issues/new?template=2_bug.md
flutter:
flutter: The relevant error-causing widget was:
flutter:   AutoRouter
```

and my MaterialApp:

```dart

 static FirebaseAnalytics analytics = FirebaseAnalytics();
  static FirebaseAnalyticsObserver observer =
      FirebaseAnalyticsObserver(analytics: analytics);

//...

MaterialApp.router(
        title: 'App',
        theme: MainTheme.lightTheme,
        darkTheme: MainTheme.darkTheme,
        routerDelegate:
            appRouter.delegate(navigatorObservers: () => [observer]),
        routeInformationParser: appRouter.defaultRouteParser(),
        builder: (context, widget) {
          return DevicePreview.appBuilder(context, widget);
        },
        supportedLocales: S.delegate.supportedLocales,
        localizationsDelegates: const [
          S.delegate,
          GlobalMaterialLocalizations.delegate,
          GlobalWidgetsLocalizations.delegate,
          GlobalCupertinoLocalizations.delegate,
        ],
      ),
```

Would you advice me what is wrong with this? Without observers it's fine

**Comment by Milad-Akarie** [comment] 2021-05-05 13:46
@Chojecki  ya I see the issue, navigatorObservers builder must return new instances everytime it's called because we can't use the same observer for different Navigators ( restricted by the native navigator) so all you have to do to fix this is treat navigatorObservers as a create function.
so just replace this line
`navigatorObservers:  ()=> [observer]`
with this
`navigatorObservers ()=> [FirebaseAnalyticsObserver(analytics: analytics)];`

**Comment by Chojecki** [comment] 2021-05-05 13:55
@Milad-Akarie make sense. Works! Thanks!
