### ISSUE TITLE
auto_route_generator 5.0.3 didn't add package alias before Color

### ISSUE THREAD

**Issue by JimmyTai** [Milad-Akarie/auto_route_library#1356] opened 2023-02-14 17:41 UTC
build_runner version: 2.3.3

This was generated by 5.0.2.
```dart
// **************************************************************************
// AutoRouteGenerator
// **************************************************************************

// GENERATED CODE - DO NOT MODIFY BY HAND

// **************************************************************************
// AutoRouteGenerator
// **************************************************************************
//
// ignore_for_file: type=lint

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:auto_route/auto_route.dart' as _i2;
import 'package:flutter/material.dart' as _i3;

import 'main.dart' as _i1;

class AppRouter extends _i2.RootStackRouter {
  AppRouter([_i3.GlobalKey<_i3.NavigatorState>? navigatorKey])
      : super(navigatorKey);

  @override
  final Map<String, _i2.PageFactory> pagesMap = {
    MyHomeRoute.name: (routeData) {
      final args = routeData.argsAs<MyHomeRouteArgs>();
      return _i2.MaterialPageX<dynamic>(
        routeData: routeData,
        child: _i1.MyHomePage(
          key: args.key,
          title: args.title,
          backgroundColor: args.backgroundColor,
        ),
      );
    }
  };

  @override
  List<_i2.RouteConfig> get routes => [
        _i2.RouteConfig(
          MyHomeRoute.name,
          path: '/my-home-page',
        )
      ];
}

/// generated route for
/// [_i1.MyHomePage]
class MyHomeRoute extends _i2.PageRouteInfo<MyHomeRouteArgs> {
  MyHomeRoute({
    _i3.Key? key,
    required String title,
    _i3.Color backgroundColor = _i3.Colors.transparent,
  }) : super(
          MyHomeRoute.name,
          path: '/my-home-page',
          args: MyHomeRouteArgs(
            key: key,
            title: title,
            backgroundColor: backgroundColor,
          ),
        );

  static const String name = 'MyHomeRoute';
}

class MyHomeRouteArgs {
  const MyHomeRouteArgs({
    this.key,
    required this.title,
    this.backgroundColor = _i3.Colors.transparent,
  });

  final _i3.Key? key;

  final String title;

  final _i3.Color backgroundColor;

  @override
  String toString() {
    return 'MyHomeRouteArgs{key: $key, title: $title, backgroundColor: $backgroundColor}';
  }
}

```

This was generated by 5.0.3
```dart
// **************************************************************************
// AutoRouteGenerator
// **************************************************************************

// GENERATED CODE - DO NOT MODIFY BY HAND

// **************************************************************************
// AutoRouteGenerator
// **************************************************************************
//
// ignore_for_file: type=lint

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:auto_route/auto_route.dart' as _i2;
import 'package:flutter/material.dart' as _i3;

import 'main.dart' as _i1;

class AppRouter extends _i2.RootStackRouter {
  AppRouter([_i3.GlobalKey<_i3.NavigatorState>? navigatorKey])
      : super(navigatorKey);

  @override
  final Map<String, _i2.PageFactory> pagesMap = {
    MyHomeRoute.name: (routeData) {
      final args = routeData.argsAs<MyHomeRouteArgs>();
      return _i2.MaterialPageX<dynamic>(
        routeData: routeData,
        child: _i1.MyHomePage(
          key: args.key,
          title: args.title,
          backgroundColor: args.backgroundColor,
        ),
      );
    }
  };

  @override
  List<_i2.RouteConfig> get routes => [
        _i2.RouteConfig(
          MyHomeRoute.name,
          path: '/my-home-page',
        )
      ];
}

/// generated route for
/// [_i1.MyHomePage]
class MyHomeRoute extends _i2.PageRouteInfo<MyHomeRouteArgs> {
  MyHomeRoute({
    _i3.Key? key,
    required String title,
    dynamic backgroundColor = Colors.transparent,
  }) : super(
          MyHomeRoute.name,
          path: '/my-home-page',
          args: MyHomeRouteArgs(
            key: key,
            title: title,
            backgroundColor: backgroundColor,
          ),
        );

  static const String name = 'MyHomeRoute';
}

class MyHomeRouteArgs {
  const MyHomeRouteArgs({
    this.key,
    required this.title,
    this.backgroundColor = Colors.transparent,
  });

  final _i3.Key? key;

  final String title;

  final dynamic backgroundColor;

  @override
  String toString() {
    return 'MyHomeRouteArgs{key: $key, title: $title, backgroundColor: $backgroundColor}';
  }
}

```

**Comment by simplenotezy** [comment] 2023-03-22 18:00
Duplicate of https://github.com/Milad-Akarie/auto_route_library/issues/1348

**Comment by Milad-Akarie** [comment] 2023-03-22 19:23
@JimmyTai @simplenotezy I just debuged this, the main issue is that `Color` type ( speceifcally )  form material package is not analyzed as a type, you can see how it's a `dynamic` in the above code, you can also try with other types and it works as before. 
now this issue could be from the `analyzer`, `source_gen` or flutter framework it self.  I'll try to dig deeper into this but it's better you work around it for now.

**Comment by simplenotezy** [comment] 2023-03-22 19:25
@Milad-Akarie it reminds me of this: https://github.com/rrousselGit/riverpod/issues/2036

What I ended up doing was renaming my model from `Image` to `ImageModel` as a workaround

**Comment by Milad-Akarie** [comment] 2023-03-22 19:29
@simplenotezy  I tried to typedef the color but it still didn't work, 
`type ColorType = m.Color;`
it's propaply the analyzer doing, can't just downgrade because alot of packages are using 5+ version.

**Comment by Milad-Akarie** [comment] 2023-03-22 19:51
@simplenotezy I'll see what I can do, bare in mind that now generated graphs are cached more efficiently by the `build_runner` and supposedly the very first time will take some time but then only new file should be processed.

**Comment by simplenotezy** [comment] 2023-03-25 20:04
> @simplenotezy I'll see what I can do, bare in mind that now generated graphs are cached more efficiently by the `build_runner` and supposedly the very first time will take some time but then only new files should be processed. 

Nice. What version is this? Because currently builds take 30-40 seconds when saving even simple widget files :/

**Comment by Milad-Akarie** [comment] 2023-03-25 21:55
@simplenotezy this seems to work 

```yaml
targets:
  $default:
    builders:
      auto_route_generator:auto_route_generator:
        generate_for: [ lib/ui/**_screen.dart ]
      auto_route_generator:auto_router_generator:
        generate_for: [ lib/ui/router/router.dart ]

```

**Comment by simplenotezy** [comment] 2023-03-26 20:44
@Milad-Akarie Defiantly did a lot - down to 20 seconds when saving a Widget file, thanks! 🎉 

Still don't quite understand why it runs the auto_route_generator on this file: `interest_form_field`, when the configuration is like so:

```yaml
      auto_route_generator:auto_route_generator:
        generate_for:
          - lib/flutter_splash_screen.dart
          - lib/playground.dart
          - lib/**/presentation/**/*.dart
          - lib/**/presentation/*.dart
      auto_route_generator:auto_router_generator:
        generate_for: [ lib/features/router/router.dart ]
```


Log output:

[FINE] auto_route_generator on lib/features/profile/presentation/edit_profile/widgets/interest_form_field.dart:Running AutoRouteGenerator

Perhaps it's related to https://github.com/dart-lang/build/issues/3448 ?

**Comment by Milad-Akarie** [comment] 2023-03-26 20:50
Im on to something, I'm working on some kind of auto_route exclusive cache mechanism, if it works as expected generation time will be alot faster

**Closed** 2023-06-05 08:21 UTC
Labels: no-issue-activity
