### ISSUE TITLE
Question about auth guard lose state after refresh the web page

### ISSUE THREAD

**Issue by AscentionOne** [Milad-Akarie/auto_route_library#374] opened 2021-02-26 08:29 UTC
I am currently working on a project and set the "Home page" as my initial route with an auth guard. The functionality of auth guard is pretty simple... first, check whether the user is authenticated or not. If yes, navigate to "Home page" and if not navigate to "Sign in page". When the user press the sign out button navigate to "Home page", the auth guard will do its work again.

The process works fine until we press the refresh page button on the web bar next to URL. Here is the workflow.

Condition 1: user open the web page (because auth guard) -> sign in page (successfully sign in) -> home page  (works fine👍)

Here is where the issue.

Condition 2: user opens the web page (because auth guard) -> sign in page (successfully sign in) -> home page -> sign out -> navigate to  home page, because auth guard -> sign in page (when I press the refresh button now and sign in successfully the page will still be on sign in page and will not navigate to home page!) 

However, when we manually type in the url to home page. Ex: /home. I can navigate to home page because I am signed in successfully. Which passes the auth guard.

My suspect is that when we navigate to home page and auth guard navigate us to the sign in page. It is still waiting for the call back from sign in page to return `true`. When we refresh the web page now, the auth guard is lost (possible the home page route in the stack? not sure ...) and does not know what to do after successfully sign in.

Anyone have this issue before? or how should I do it correctly? Thanks in advance!

My route set up in simple:

``` dart
@MaterialAutoRouter(
  routes: <AutoRoute>[
 AutoRoute( path: '/signin', page: SignInPage ),
 AutoRoute( path: '/', page: HomePage, inital:true, guards: [AuthGuard] ),
  ],
)
class $AppRouter {}
``` 

Here is my auth guard:

``` dart
class AuthGuard extends AutoRouteGuard {
  @override
  Future<bool> canNavigate(
      List<PageRouteInfo> pendingRoutes, StackRouter router) async {

    if (isAuthenticated) {
       router.root.push(SignInRout(onLoginResult: (success) {
        if (success) {
          router.replaceAll(pendingRoutes);
        }
      }));
      return false;
    }
    return true;
  }
}
```

**Comment by theweiweiway** [comment] 2021-02-27 03:15
Hey @AscentionOne 

I think this issue is related to #290 - something to do with the order that routes are pushed and when the guard is initialized with respect to the order of how the routes are pushed.

**Comment by AscentionOne** [comment] 2021-02-28 01:59
Hi @theweiweiway thank you for the reply!

Seems like the issue Milan mention in #290. The guard is activated before the navigator key got mounted. So after refreshing the web page. The navigator key is gone? But still not so sure... Hope this will have a solution soon, currently is developing the project and kinda stuck.

@Milad-Akarie Do you have any thoughts about this? Thank you, I really like auto route package a lot and hope to use it along with my project. 😝

**Comment by theweiweiway** [comment] 2021-03-30 13:12
Hey - pretty sure this is caused by #290 so I"m going to close this issue in the meantime

**Closed by theweiweiway** 2021-03-30 13:12 UTC
Labels: bug
